name: rewint
description: read write count
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  awesome_dialog: ^2.2.1
  blurhash_flutter: ^0.1.0
  camera: ^0.10.0
  cloud_firestore: 3.1.5
  cupertino_icons: ^1.0.2
  easy_separator: ^1.0.1
  firebase_auth: ^3.3.5
  firebase_core: ^1.20.0
  firebase_storage: ^10.2.5
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.2.0
  flutter_screenutil: ^5.5.3+2
  flutter_svg: ^1.0.0
  flutter_tts: ^3.5.0
  flutter_zoom_drawer: ^2.1.2
  get: ^4.6.5
  google_fonts: ^2.2.0
  google_mlkit_digital_ink_recognition: ^0.4.0
  google_mlkit_object_detection: ^0.4.0
  google_sign_in: ^5.2.1
  hexcolor: ^2.0.7
  http: ^0.13.4
  image_picker: ^0.8.5+3
  liquid_pull_to_refresh: ^3.0.1
  logger: ^1.0.0
  path_provider: ^2.0.8
  shimmer: ^2.0.0
  speech_to_text: ^5.6.0
  url_launcher: ^6.0.18
  youtube_player_flutter: ^8.1.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/models/
    - assets/images/
    - assets/icons/
    - assets/DB/papers/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/icons/AppIcons.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages

# flutter_native_splash:
#   color: "#7424ed"
#   color_dark: "#5d0ed2"
#   android_gravity: center
#   fullscreen: true
#   image: assets/images/app_splash_logo.png
