// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHvkVLGOT6H8MJTGmRW6FPHZ353t3WsNM',
    appId: '1:387456396160:web:bc776f33205d3cdf302f65',
    messagingSenderId: '387456396160',
    projectId: 'rewint-f218b',
    authDomain: 'rewint-f218b.firebaseapp.com',
    storageBucket: 'rewint-f218b.appspot.com',
    measurementId: 'G-S318MRHB2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrX8saw5JG330211LnwuTw-U-E5hby5r4',
    appId: '1:387456396160:android:d8b5f7aea16f3d3a302f65',
    messagingSenderId: '387456396160',
    projectId: 'rewint-f218b',
    storageBucket: 'rewint-f218b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGOKqvE_3u1bF1WzJymXUlUo_pgtcFqLU',
    appId: '1:387456396160:ios:7872f50932244067302f65',
    messagingSenderId: '387456396160',
    projectId: 'rewint-f218b',
    storageBucket: 'rewint-f218b.appspot.com',
    iosClientId: '387456396160-8v5ghqis1nqapuvs8oeb7gk4b4bvmr7j.apps.googleusercontent.com',
    iosBundleId: 'com.codefox.rewint',
  );
}
