name: 🔨🧪 Build & Test

permissions: write-all

on:
  pull_request:
    branches:
      - "master"
    tags:
      - "v*.*.*"

jobs:
  deploy:
    name: 🔨 Deploy
    uses: ./.github/workflows/deploy.yml
